services:
  - type: web
    name: sok-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-connection-string
